# PPD dos dados para treinamento, validação e teste

In [1]:
##importando bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import random
from numpy import median, mean
from sklearn import svm
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import LocalOutlierFactor
from sklearn.covariance import EllipticEnvelope
from sklearn.ensemble import IsolationForest

* Outlier =  1 normal
* Outlier = -1 anormal

## IMPORTANDO dados treinamento, validacao e teste

In [2]:
#cclothes

In [3]:
## importando dataset VALIDACAO
df_cclothes_trein = pd.read_csv('dataseteh/pp4/eh-ativ-cclothes-treinfull.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_cclothes_trein.shape)
df_cclothes_trein.head()

(366, 7)

   dia  dia_semana  fim_semana  duracao  frequencia     durfreq  outlier
0    1           0           0   1319.0         3.0  439.666667        1
1    2           1           0   1242.0         3.0  414.000000        1
2    3           2           0   1513.0         3.0  504.333333        1
3    4           3           0    959.0         2.0  479.500000        1
4    5           4           0    947.0         2.0  473.500000        1

In [4]:
## importando dataset VALIDACAO
df_cclothes_valid = pd.read_csv('dataseteh/pp4/eh-ativ-cclothes-valid84.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_cclothes_valid.shape)
df_cclothes_valid.head()

(84, 7)

   dia  dia_semana  fim_semana  duracao  frequencia     durfreq  outlier
0    1           0           0   1124.0         2.0  562.000000        1
1    2           1           0    811.0         2.0  405.500000        1
2    3           2           0   1160.0         3.0  386.666667        1
3    4           3           0    876.0         2.0  438.000000        1
4    5           4           0    691.0         2.0  345.500000        1

In [5]:
## importando dataset de TESTE
df_cclothes_test = pd.read_csv('dataseteh/pp4/eh-ativ-cclothes-test84.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_cclothes_test.shape)
df_cclothes_test.head()

(84, 7)

   dia  dia_semana  fim_semana  duracao  frequencia     durfreq  outlier
0    1           0           0   1124.0         2.0  562.000000        1
1    2           1           0    811.0         2.0  405.500000        1
2    3           2           0   1160.0         3.0  386.666667        1
3    4           3           0    876.0         2.0  438.000000        1
4    5           4           0    490.0         2.0  190.000000       -1

In [6]:
#eating

In [7]:
## importando dataset VALIDACAO
df_eating_trein = pd.read_csv('dataseteh/pp4/eh-ativ-eating-treinfull.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_eating_trein.shape)
df_eating_trein.head()

(366, 7)

   dia  dia_semana  fim_semana  duracao  frequencia      durfreq  outlier
0    1           0           0   4407.0         2.0  2203.500000        1
1    2           1           0   7409.0         3.0  2469.666667        1
2    3           2           0   3845.0         2.0  1922.500000        1
3    4           3           0   7010.0         3.0  2336.666667        1
4    5           4           0   8027.0         3.0  2675.666667        1

In [8]:
## importando dataset VALIDACAO
df_eating_valid = pd.read_csv('dataseteh/pp4/eh-ativ-eating-valid84.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_eating_valid.shape)
df_eating_valid.head()

(84, 7)

   dia  dia_semana  fim_semana  duracao  frequencia      durfreq  outlier
0    1           0           0   4254.0         2.0  2127.000000        1
1    2           1           0   7614.0         3.0  2538.000000        1
2    3           2           0   7642.0         3.0  2547.333333        1
3    4           3           0   7297.0         3.0  2432.333333        1
4    5           4           0   3682.0         2.0  1841.000000        1

In [9]:
## importando dataset de TESTE
df_eating_test = pd.read_csv('dataseteh/pp4/eh-ativ-eating-test84.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_eating_test.shape)
df_eating_test.head()

(84, 7)

   dia  dia_semana  fim_semana  duracao  frequencia      durfreq  outlier
0    1           0           0   3318.0         2.0  1359.000000       -1
1    2           1           0   7614.0         3.0  2538.000000        1
2    3           2           0   7642.0         3.0  2547.333333        1
3    4           3           0   9777.0         1.0  4938.000000       -1
4    5           4           0   2651.0         2.0  1035.000000       -1

In [10]:
#mcoffe

In [11]:
## importando dataset VALIDACAO
df_mcoffe_trein = pd.read_csv('dataseteh/pp4/eh-ativ-mcoffe-treinfull.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_mcoffe_trein.shape)
df_mcoffe_trein.head()

(366, 7)

   dia  dia_semana  fim_semana  duracao  frequencia     durfreq  outlier
0    1           0           0   1600.0         4.0  400.000000        1
1    2           1           0   2122.0         5.0  424.400000        1
2    3           2           0   1157.0         3.0  385.666667        1
3    4           3           0   1400.0         3.0  466.666667        1
4    5           4           0    846.0         2.0  423.000000        1

In [12]:
## importando dataset VALIDACAO
df_mcoffe_valid = pd.read_csv('dataseteh/pp4/eh-ativ-mcoffe-valid84.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_mcoffe_valid.shape)
df_mcoffe_valid.head()

(84, 7)

   dia  dia_semana  fim_semana  duracao  frequencia     durfreq  outlier
0    1           0           0   1386.0         3.0  462.000000        1
1    2           1           0   1069.0         3.0  356.333333        1
2    3           2           0   1426.0         3.0  475.333333        1
3    4           3           0   1715.0         4.0  428.750000        1
4    5           4           0    493.0         1.0  493.000000        1

In [13]:
## importando dataset de TESTE
df_mcoffe_test = pd.read_csv('dataseteh/pp4/eh-ativ-mcoffe-test84.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_mcoffe_test.shape)
df_mcoffe_test.head()

(84, 7)

   dia  dia_semana  fim_semana  duracao  frequencia     durfreq  outlier
0    1           0           0    928.0         3.0  232.000000       -1
1    2           1           0   1069.0         3.0  356.333333        1
2    3           2           0   1083.0         3.0  291.000000       -1
3    4           3           0   2178.0         2.0  745.000000       -1
4    5           4           0    374.0         1.0  302.000000       -1

In [14]:
#mhotfood

In [15]:
## importando dataset VALIDACAO
df_mhotfood_trein = pd.read_csv('dataseteh/pp4/eh-ativ-mhotfood-treinfull.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_mhotfood_trein.shape)
df_mhotfood_trein.head()

(366, 7)

   dia  dia_semana  fim_semana  duracao  frequencia  durfreq  outlier
0    1           0           0   2684.0         1.0   2684.0        1
1    2           1           0   4710.0         2.0   2355.0        1
2    3           2           0   6173.0         2.0   3086.5        1
3    4           3           0   5820.0         2.0   2910.0        1
4    5           4           0   5823.0         2.0   2911.5        1

In [16]:
## importando dataset VALIDACAO
df_mhotfood_valid = pd.read_csv('dataseteh/pp4/eh-ativ-mhotfood-valid84.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_mhotfood_valid.shape)
df_mhotfood_valid.head()

(84, 7)

   dia  dia_semana  fim_semana  duracao  frequencia  durfreq  outlier
0    1           0           0   2419.0         1.0   2419.0        1
1    2           1           0   4841.0         2.0   2420.5        1
2    3           2           0   5846.0         2.0   2923.0        1
3    4           3           0   4003.0         2.0   2001.5        1
4    5           4           0   2896.0         1.0   2896.0        1

In [17]:
## importando dataset de TESTE
df_mhotfood_test = pd.read_csv('dataseteh/pp4/eh-ativ-mhotfood-test84.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_mhotfood_test.shape)
df_mhotfood_test.head()

(84, 7)

   dia  dia_semana  fim_semana  duracao  frequencia  durfreq  outlier
0    1           0           0   1596.0         1.0   1191.0       -1
1    2           1           0   4841.0         2.0   2420.5        1
2    3           2           0   5846.0         2.0   2923.0        1
3    4           3           0   2601.0         2.0    963.0       -1
4    5           4           0   2896.0         1.0   2896.0        1

In [18]:
#sleep

In [19]:
## importando dataset VALIDACAO
df_sleep_trein = pd.read_csv('dataseteh/pp4/eh-ativ-sleep-treinfull.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_sleep_trein.shape)
df_sleep_trein.head()

(366, 7)

   dia  dia_semana  fim_semana  duracao  frequencia       durfreq  outlier
0    1           1           0  24939.0         2.0  12469.500000        1
1    2           2           0  47166.0         3.0  15722.000000        1
2    3           3           0  43603.0         3.0  14534.333333        1
3    4           4           0  37225.0         3.0  12408.333333        1
4    5           5           1  44044.0         3.0  14681.333333        1

In [20]:
## importando dataset VALIDACAO
df_sleep_valid = pd.read_csv('dataseteh/pp4/eh-ativ-sleep-valid84.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_sleep_valid.shape)
df_sleep_valid.head()

(84, 7)

   dia  dia_semana  fim_semana  duracao  frequencia       durfreq  outlier
0    1           1           0  41311.0         3.0  13770.333333        1
1    2           2           0  48280.0         3.0  16093.333333        1
2    3           3           0  48276.0         3.0  16092.000000        1
3    4           4           0  42558.0         3.0  14186.000000        1
4    5           5           1  35394.0         3.0  11798.000000        1

In [21]:
## importando dataset de TESTE
df_sleep_test = pd.read_csv('dataseteh/pp4/eh-ativ-sleep-test84.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_sleep_test.shape)
df_sleep_test.head()

(84, 7)

   dia  dia_semana  fim_semana  duracao  frequencia       durfreq  outlier
0    1           1           0  41311.0         3.0  13770.333333        1
1    2           2           0  62764.0         1.0  33744.000000       -1
2    3           3           0  63724.0         1.0  41649.000000       -1
3    4           4           0  52346.0         2.0  24926.000000       -1
4    5           5           1  35394.0         3.0  11798.000000        1

In [22]:
#toileting

In [23]:
## importando dataset VALIDACAO
df_toileting_trein = pd.read_csv('dataseteh/pp4/eh-ativ-toileting-treinfull.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_toileting_trein.shape)
df_toileting_trein.head()

(366, 7)

   dia  dia_semana  fim_semana  duracao  frequencia     durfreq  outlier
0    1           0           0   2840.0         6.0  473.333333        1
1    2           1           0   1937.0         4.0  484.250000        1
2    3           2           0   2800.0         7.0  400.000000        1
3    4           3           0   2401.0         5.0  480.200000        1
4    5           4           0   1429.0         3.0  476.333333        1

In [24]:
## importando dataset VALIDACAO
df_toileting_valid = pd.read_csv('dataseteh/pp4/eh-ativ-toileting-valid84.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_toileting_valid.shape)
df_toileting_valid.head()

(84, 7)

   dia  dia_semana  fim_semana  duracao  frequencia     durfreq  outlier
0    1           0           0   3362.0         7.0  480.285714        1
1    2           1           0   1341.0         3.0  447.000000        1
2    3           2           0   3842.0         8.0  480.250000        1
3    4           3           0   2679.0         6.0  446.500000        1
4    5           4           0   1335.0         4.0  333.750000        1

In [25]:
## importando dataset de TESTE
df_toileting_test = pd.read_csv('dataseteh/pp4/eh-ativ-toileting-test84.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_toileting_test.shape)
df_toileting_test.head()

(84, 7)

   dia  dia_semana  fim_semana  duracao  frequencia  durfreq  outlier
0    1           0           0   4942.0         3.0  1332.00       -1
1    2           1           0   1622.0         2.0   684.00       -1
2    3           2           0   3842.0         8.0   480.25        1
3    4           3           0   3429.0         4.0   793.00       -1
4    5           4           0    827.0         5.0   149.00       -1

In [26]:
#whandface

In [27]:
## importando dataset VALIDACAO
df_whandface_trein = pd.read_csv('dataseteh/pp4/eh-ativ-whandface-treinfull.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_whandface_trein.shape)
df_whandface_trein.head()

(366, 7)

   dia  dia_semana  fim_semana  duracao  frequencia     durfreq  outlier
0    1           0           0   2971.0        10.0  297.100000        1
1    2           1           0   2659.0        10.0  265.900000        1
2    3           2           0   2359.0         8.0  294.875000        1
3    4           3           0   2862.0        11.0  260.181818        1
4    5           4           0   1066.0         4.0  266.500000        1

In [28]:
## importando dataset VALIDACAO
df_whandface_valid = pd.read_csv('dataseteh/pp4/eh-ativ-whandface-valid84.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_whandface_valid.shape)
df_whandface_valid.head()

(84, 7)

   dia  dia_semana  fim_semana  duracao  frequencia     durfreq  outlier
0    1           0           0   3019.0        11.0  274.454545        1
1    2           1           0   2359.0         9.0  262.111111        1
2    3           2           0   3329.0        11.0  302.636364        1
3    4           3           0   3664.0        14.0  261.714286        1
4    5           4           0   2097.0         8.0  262.125000        1

In [29]:
## importando dataset de TESTE
df_whandface_test = pd.read_csv('dataseteh/pp4/eh-ativ-whandface-test84.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_whandface_test.shape)
df_whandface_test.head()

(84, 7)

   dia  dia_semana  fim_semana  duracao  frequencia     durfreq  outlier
0    1           0           0   3019.0        11.0  274.454545        1
1    2           1           0   3137.0         6.0  520.000000       -1
2    3           2           0   2097.0        15.0  139.000000       -1
3    4           3           0   2564.0        18.0  140.000000       -1
4    5           4           0   2097.0         8.0  262.125000        1

In [30]:
#watchtv

In [31]:
## importando dataset VALIDACAO
df_watchtv_trein = pd.read_csv('dataseteh/pp4/eh-ativ-watchtv-treinfull.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_watchtv_trein.shape)
df_watchtv_trein.head()

(366, 7)

   dia  dia_semana  fim_semana  duracao  frequencia      durfreq  outlier
0    1           1           0  10366.0         2.0  5183.000000        1
1    2           2           0   5679.0         2.0  2839.500000        1
2    3           3           0  11060.0         5.0  2212.000000        1
3    4           4           0  12403.0         3.0  4134.333333        1
4    5           5           1  10864.0         5.0  2172.800000        1

In [32]:
## importando dataset VALIDACAO
df_watchtv_valid = pd.read_csv('dataseteh/pp4/eh-ativ-watchtv-valid84.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_watchtv_valid.shape)
df_watchtv_valid.head()

(84, 7)

   dia  dia_semana  fim_semana  duracao  frequencia  durfreq  outlier
0    1           1           0   7982.0         2.0   3991.0        1
1    2           2           0  10017.0         3.0   3339.0        1
2    3           3           0   8824.0         4.0   2206.0        1
3    4           4           0   4021.0         2.0   2010.5        1
4    5           5           1  16540.0         4.0   4135.0        1

In [33]:
## importando dataset de TESTE
df_watchtv_test = pd.read_csv('dataseteh/pp4/eh-ativ-watchtv-test84.csv',delimiter=';',decimal=',',thousands=".",encoding='ANSI')
print(df_watchtv_test.shape)
df_watchtv_test.head()

(84, 7)

   dia  dia_semana  fim_semana  duracao  frequencia  durfreq  outlier
0    1           1           0   7982.0         2.0   3991.0        1
1    2           2           0  10017.0         3.0   3339.0        1
2    3           3           0  11382.0         2.0   4065.0       -1
3    4           4           0   2412.0         2.0    867.0       -1
4    5           5           1  16540.0         4.0   4135.0        1

## Treinando MODELOS (4) para SEMANAS (20)

In [34]:
for z in range (1,6): # iterando atividades 1 cclothes, 2 eating
                      # 3 mcoffe, 4 mhotfood, 5 toileting e 6 whandface
    for y in range (1,5): # iterando algoritmos 1 OC-SVM, 2 LOF, 3 iForest e 4 RCE
        # inicializando listas temporárias para armazenar as métricas
        csemana = []
        cvp = []
        cvn = []
        cfp = []
        cfn = []
        cacuracia = []
        cprecisao = []
        csensibilidade = []
        cf1escore = []
        for x in range(1,20): #iterando nas semanas 2 a 20 (x+1)
                              #de dados de treinamento
            semana = x+1
            if z==1: #cclothes
                p1testes = df_cclothes_test.iloc[:, [1,2,3,4,5]].copy()
                p1treins = df_cclothes_trein.iloc[0:semana*7].copy()
                p1treins = p1treins.iloc[:, [1,2,3,4,5]]
                atividade = 'cclothes'            
            if z==2: #eating
                p1testes = df_eating_test.iloc[:, [1,2,3,4,5]].copy()
                p1treins = df_eating_trein.iloc[0:semana*7].copy()
                p1treins = p1treins.iloc[:, [1,2,3,4,5]]
                atividade = 'eating'
            if z==3: #mcoffe
                p1testes = df_mcoffe_test.iloc[:, [1,2,3,4,5]].copy()
                p1treins = df_mcoffe_trein.iloc[0:semana*7].copy()
                p1treins = p1treins.iloc[:, [1,2,3,4,5]]
                atividade = 'mcoffe'
            if z==4: #mhotfood
                p1testes = df_mhotfood_test.iloc[:, [1,2,3,4,5]].copy()
                p1treins = df_mhotfood_trein.iloc[0:semana*7].copy()
                p1treins = p1treins.iloc[:, [1,2,3,4,5]]
                atividade = 'mhotfood'
            if z==5: #toileting
                p1testes = df_toileting_test.iloc[:, [1,2,3,4,5]].copy()
                p1treins = df_toileting_trein.iloc[0:semana*7].copy()
                p1treins = p1treins.iloc[:, [1,2,3,4,5]]                
                atividade = 'toileting'
            if z==6: #whandface
                p1testes = df_whandface_test.iloc[:, [1,2,3,4,5]].copy()
                p1treins = df_whandface_trein.iloc[0:semana*7].copy()
                p1treins = p1treins.iloc[:, [1,2,3,4,5]]                
                atividade = 'whandface'
            #standarização
            scaler = StandardScaler().fit(p1treins)
            p1treins = scaler.transform(p1treins).copy()
            p1testes = scaler.transform(p1testes).copy()

            # treinamento dos modelos
            if y == 1:
                clf = svm.OneClassSVM(nu=0.1, kernel='rbf', gamma='scale')
                algoritmo = 'ocsvm'
            if y == 2:
                clf = LocalOutlierFactor(n_neighbors=10, novelty=True)
                algoritmo = 'lof'
            if y == 3:
                clf = IsolationForest(contamination= 0.01, random_state=1)
                algoritmo = 'iforest'
            if y == 4:
                clf = EllipticEnvelope(contamination= 0.01, random_state=0, support_fraction= 0.9)
                algoritmo = 'rce'
            clf.fit(p1treins)
            y_pred_train = clf.predict(p1treins)
            y_pred_teste = clf.predict(p1testes)

            #extração das métricas
            n_error_train = y_pred_train[y_pred_train == -1].size
            n_error_teste = y_pred_teste[y_pred_teste ==  1].size
            # calculando métricas
            if z==1: #cclothes
                df_cclothes_test['predicao'] = y_pred_teste
                df_cclothes_test['vp'] = np.where((df_cclothes_test['outlier'] == -1) & (df_cclothes_test['predicao'] == -1), 1,0)
                df_cclothes_test['vn'] = np.where((df_cclothes_test['outlier'] == 1) & (df_cclothes_test['predicao'] == 1), 1,0)
                df_cclothes_test['fp'] = np.where((df_cclothes_test['outlier'] == -1) & (df_cclothes_test['predicao'] == 1), 1,0)
                df_cclothes_test['fn'] = np.where((df_cclothes_test['outlier'] == 1) & (df_cclothes_test['predicao'] == -1), 1,0)
                VP = df_cclothes_test['vp'].sum()
                VN = df_cclothes_test['vn'].sum()
                FP = df_cclothes_test['fp'].sum()
                FN = df_cclothes_test['fn'].sum()              
            if z==2: #eating               
                df_eating_test['predicao'] = y_pred_teste
                df_eating_test['vp'] = np.where((df_eating_test['outlier'] == -1) & (df_eating_test['predicao'] == -1), 1,0)
                df_eating_test['vn'] = np.where((df_eating_test['outlier'] == 1) & (df_eating_test['predicao'] == 1), 1,0)
                df_eating_test['fp'] = np.where((df_eating_test['outlier'] == -1) & (df_eating_test['predicao'] == 1), 1,0)
                df_eating_test['fn'] = np.where((df_eating_test['outlier'] == 1) & (df_eating_test['predicao'] == -1), 1,0)
                VP = df_eating_test['vp'].sum()
                VN = df_eating_test['vn'].sum()
                FP = df_eating_test['fp'].sum()
                FN = df_eating_test['fn'].sum()                
            if z==3: #mcoffe
                df_mcoffe_test['predicao'] = y_pred_teste
                df_mcoffe_test['vp'] = np.where((df_mcoffe_test['outlier'] == -1) & (df_mcoffe_test['predicao'] == -1), 1,0)
                df_mcoffe_test['vn'] = np.where((df_mcoffe_test['outlier'] == 1) & (df_mcoffe_test['predicao'] == 1), 1,0)
                df_mcoffe_test['fp'] = np.where((df_mcoffe_test['outlier'] == -1) & (df_mcoffe_test['predicao'] == 1), 1,0)
                df_mcoffe_test['fn'] = np.where((df_mcoffe_test['outlier'] == 1) & (df_mcoffe_test['predicao'] == -1), 1,0)
                VP = df_mcoffe_test['vp'].sum()
                VN = df_mcoffe_test['vn'].sum()
                FP = df_mcoffe_test['fp'].sum()
                FN = df_mcoffe_test['fn'].sum()                   
            if z==4: #mhotfood           
                df_mhotfood_test['predicao'] = y_pred_teste
                df_mhotfood_test['vp'] = np.where((df_mhotfood_test['outlier'] == -1) & (df_mhotfood_test['predicao'] == -1), 1,0)
                df_mhotfood_test['vn'] = np.where((df_mhotfood_test['outlier'] == 1) & (df_mhotfood_test['predicao'] == 1), 1,0)
                df_mhotfood_test['fp'] = np.where((df_mhotfood_test['outlier'] == -1) & (df_mhotfood_test['predicao'] == 1), 1,0)
                df_mhotfood_test['fn'] = np.where((df_mhotfood_test['outlier'] == 1) & (df_mhotfood_test['predicao'] == -1), 1,0)
                VP = df_mhotfood_test['vp'].sum()
                VN = df_mhotfood_test['vn'].sum()
                FP = df_mhotfood_test['fp'].sum()                
            if z==5: #toileting
                df_toileting_test['predicao'] = y_pred_teste
                df_toileting_test['vp'] = np.where((df_toileting_test['outlier'] == -1) & (df_toileting_test['predicao'] == -1), 1,0)
                df_toileting_test['vn'] = np.where((df_toileting_test['outlier'] == 1) & (df_toileting_test['predicao'] == 1), 1,0)
                df_toileting_test['fp'] = np.where((df_toileting_test['outlier'] == -1) & (df_toileting_test['predicao'] == 1), 1,0)
                df_toileting_test['fn'] = np.where((df_toileting_test['outlier'] == 1) & (df_toileting_test['predicao'] == -1), 1,0)
                VP = df_toileting_test['vp'].sum()
                VN = df_toileting_test['vn'].sum()
                FP = df_toileting_test['fp'].sum()                
            if z==6: #whandface
                df_whandface_test['predicao'] = y_pred_teste
                df_whandface_test['vp'] = np.where((df_whandface_test['outlier'] == -1) & (df_whandface_test['predicao'] == -1), 1,0)
                df_whandface_test['vn'] = np.where((df_whandface_test['outlier'] == 1) & (df_whandface_test['predicao'] == 1), 1,0)
                df_whandface_test['fp'] = np.where((df_whandface_test['outlier'] == -1) & (df_whandface_test['predicao'] == 1), 1,0)
                df_whandface_test['fn'] = np.where((df_whandface_test['outlier'] == 1) & (df_whandface_test['predicao'] == -1), 1,0)
                VP = df_whandface_test['vp'].sum()
                VN = df_whandface_test['vn'].sum()
                FP = df_whandface_test['fp'].sum()                   
            erro = (FP+FN)/(VP+VN+FP+FN) #erro
            acuracia =  (VP+VN)/(VP+VN+FP+FN) # accuracy
            precisao = (VP)/(FP+VP) # precision
            sensibilidade = VP/(FN+VP) #recall
            f1escore = 2 * ((precisao * sensibilidade)/(precisao + sensibilidade))
            #armazenando metricas temp
            csemana.append(semana)
            cvp.append(VP)
            cvn.append(VN)
            cfp.append(FP)
            cfn.append(FN)
            cacuracia.append(acuracia)
            cprecisao.append(precisao)
            csensibilidade.append(sensibilidade)
            cf1escore.append(f1escore)

        #criando um dataframe a partir das métricas    
        zipped = list(zip(csemana,cvp,cvn,cfp,cfn,cacuracia, cprecisao, csensibilidade, cf1escore))    
        dfmetricas = pd.DataFrame(zipped, columns=['semanas', 'vp', 'vn', 'fp', 'fn','acuracia',
                                                   'precisao','sensibilidade','f1score'])
        dfmetricas['algoritmo'] = algoritmo
        dfmetricas['variacao'] = '20-60'
        dfmetricas['atividade'] = atividade
        print(dfmetricas.head(20))
        #exportando dataframes para datasets
        dfmetricas.to_csv(r'dataseteh/results/ehmetricas-'+atividade+'-'+algoritmo+'.csv', sep=';', 
                          index=False, decimal=',')

    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2  25  23   0  36  0.571429      1.00       0.409836  0.581395
1         3  25  31   0  28  0.666667      1.00       0.471698  0.641026
2         4  25  38   0  21  0.750000      1.00       0.543478  0.704225
3         5  25  39   0  20  0.761905      1.00       0.555556  0.714286
4         6  25  42   0  17  0.797619      1.00       0.595238  0.746269
5         7  24  43   1  16  0.797619      0.96       0.600000  0.738462
6         8  24  43   1  16  0.797619      0.96       0.600000  0.738462
7         9  24  46   1  13  0.833333      0.96       0.648649  0.774194
8        10  24  46   1  13  0.833333      0.96       0.648649  0.774194
9        11  24  45   1  14  0.821429      0.96       0.631579  0.761905
10       12  24  44   1  15  0.809524      0.96       0.615385  0.750000
11       13  24  44   1  15  0.809524      0.96       0.615385  0.750000
12       14  24  50   1   9  0.880952      0.96       0.727273  0.827586
13       15  25  50   0   9  0.892857      1.00       0.735294  0.847458
14       16  24  51   1   8  0.892857      0.96       0.750000  0.842105
15       17  25  53   0   6  0.928571      1.00       0.806452  0.892857
16       18  25  53   0   6  0.928571      1.00       0.806452  0.892857
17       19  25  53   0   6  0.928571      1.00       0.806452  0.892857
18       20  25  53   0   6  0.928571      1.00       0.806452  0.892857

   algoritmo variacao atividade
0      ocsvm    20-60  cclothes
1      ocsvm    20-60  cclothes
2      ocsvm    20-60  cclothes
3      ocsvm    20-60  cclothes
4      ocsvm    20-60  cclothes
5      ocsvm    20-60  cclothes
6      ocsvm    20-60  cclothes
7      ocsvm    20-60  cclothes
8      ocsvm    20-60  cclothes
9      ocsvm    20-60  cclothes
10     ocsvm    20-60  cclothes
11     ocsvm    20-60  cclothes
12     ocsvm    20-60  cclothes
13     ocsvm    20-60  cclothes
14     ocsvm    20-60  cclothes
15     ocsvm    20-60  cclothes
16     ocsvm    20-60  cclothes
17     ocsvm    20-60  cclothes
18     ocsvm    20-60  cclothes
    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2  20  59   5   0  0.940476      0.80       1.000000  0.888889
1         3  21  59   4   0  0.952381      0.84       1.000000  0.913043
2         4  21  59   4   0  0.952381      0.84       1.000000  0.913043
3         5  21  59   4   0  0.952381      0.84       1.000000  0.913043
4         6  22  59   3   0  0.964286      0.88       1.000000  0.936170
5         7  22  59   3   0  0.964286      0.88       1.000000  0.936170
6         8  22  57   3   2  0.940476      0.88       0.916667  0.897959
7         9  22  57   3   2  0.940476      0.88       0.916667  0.897959
8        10  22  56   3   3  0.928571      0.88       0.880000  0.880000
9        11  22  56   3   3  0.928571      0.88       0.880000  0.880000
10       12  22  56   3   3  0.928571      0.88       0.880000  0.880000
11       13  22  57   3   2  0.940476      0.88       0.916667  0.897959
12       14  22  57   3   2  0.940476      0.88       0.916667  0.897959
13       15  22  55   3   4  0.916667      0.88       0.846154  0.862745
14       16  22  51   3   8  0.869048      0.88       0.733333  0.800000
15       17  22  53   3   6  0.892857      0.88       0.785714  0.830189
16       18  22  55   3   4  0.916667      0.88       0.846154  0.862745
17       19  22  55   3   4  0.916667      0.88       0.846154  0.862745
18       20  22  55   3   4  0.916667      0.88       0.846154  0.862745

   algoritmo variacao atividade
0        lof    20-60  cclothes
1        lof    20-60  cclothes
2        lof    20-60  cclothes
3        lof    20-60  cclothes
4        lof    20-60  cclothes
5        lof    20-60  cclothes
6        lof    20-60  cclothes
7        lof    20-60  cclothes
8        lof    20-60  cclothes
9        lof    20-60  cclothes
10       lof    20-60  cclothes
11       lof    20-60  cclothes
12       lof    20-60  cclothes
13       lof    20-60  cclothes
14       lof    20-60  cclothes
15       lof    20-60  cclothes
16       lof    20-60  cclothes
17       lof    20-60  cclothes
18       lof    20-60  cclothes

C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall

    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2   6  56  19   3  0.738095      0.24       0.666667  0.352941
1         3   2  58  23   1  0.714286      0.08       0.666667  0.142857
2         4   7  56  18   3  0.750000      0.28       0.700000  0.400000
3         5   4  59  21   0  0.750000      0.16       1.000000  0.275862
4         6   2  59  23   0  0.726190      0.08       1.000000  0.148148
5         7   4  59  21   0  0.750000      0.16       1.000000  0.275862
6         8   2  59  23   0  0.726190      0.08       1.000000  0.148148
7         9   0  59  25   0  0.702381      0.00            NaN       NaN
8        10   2  59  23   0  0.726190      0.08       1.000000  0.148148
9        11   1  59  24   0  0.714286      0.04       1.000000  0.076923
10       12   2  58  23   1  0.714286      0.08       0.666667  0.142857
11       13   1  59  24   0  0.714286      0.04       1.000000  0.076923
12       14   0  59  25   0  0.702381      0.00            NaN       NaN
13       15   0  59  25   0  0.702381      0.00            NaN       NaN
14       16   0  59  25   0  0.702381      0.00            NaN       NaN
15       17   0  59  25   0  0.702381      0.00            NaN       NaN
16       18   2  59  23   0  0.726190      0.08       1.000000  0.148148
17       19   0  59  25   0  0.702381      0.00            NaN       NaN
18       20   0  59  25   0  0.702381      0.00            NaN       NaN

   algoritmo variacao atividade
0    iforest    20-60  cclothes
1    iforest    20-60  cclothes
2    iforest    20-60  cclothes
3    iforest    20-60  cclothes
4    iforest    20-60  cclothes
5    iforest    20-60  cclothes
6    iforest    20-60  cclothes
7    iforest    20-60  cclothes
8    iforest    20-60  cclothes
9    iforest    20-60  cclothes
10   iforest    20-60  cclothes
11   iforest    20-60  cclothes
12   iforest    20-60  cclothes
13   iforest    20-60  cclothes
14   iforest    20-60  cclothes
15   iforest    20-60  cclothes
16   iforest    20-60  cclothes
17   iforest    20-60  cclothes
18   iforest    20-60  cclothes
    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2  23  56   2   3  0.940476      0.92       0.884615  0.901961
1         3  22  58   3   1  0.952381      0.88       0.956522  0.916667
2         4  25  58   0   1  0.988095      1.00       0.961538  0.980392
3         5  25  59   0   0  1.000000      1.00       1.000000  1.000000
4         6  22  59   3   0  0.964286      0.88       1.000000  0.936170
5         7  22  59   3   0  0.964286      0.88       1.000000  0.936170
6         8  22  59   3   0  0.964286      0.88       1.000000  0.936170
7         9  22  59   3   0  0.964286      0.88       1.000000  0.936170
8        10  22  59   3   0  0.964286      0.88       1.000000  0.936170
9        11  23  59   2   0  0.976190      0.92       1.000000  0.958333
10       12  23  59   2   0  0.976190      0.92       1.000000  0.958333
11       13  23  59   2   0  0.976190      0.92       1.000000  0.958333
12       14  24  59   1   0  0.988095      0.96       1.000000  0.979592
13       15  24  59   1   0  0.988095      0.96       1.000000  0.979592
14       16  24  59   1   0  0.988095      0.96       1.000000  0.979592
15       17  24  59   1   0  0.988095      0.96       1.000000  0.979592
16       18  24  59   1   0  0.988095      0.96       1.000000  0.979592
17       19  24  59   1   0  0.988095      0.96       1.000000  0.979592
18       20  24  59   1   0  0.988095      0.96       1.000000  0.979592

   algoritmo variacao atividade
0        rce    20-60  cclothes
1        rce    20-60  cclothes
2        rce    20-60  cclothes
3        rce    20-60  cclothes
4        rce    20-60  cclothes
5        rce    20-60  cclothes
6        rce    20-60  cclothes
7        rce    20-60  cclothes
8        rce    20-60  cclothes
9        rce    20-60  cclothes
10       rce    20-60  cclothes
11       rce    20-60  cclothes
12       rce    20-60  cclothes
13       rce    20-60  cclothes
14       rce    20-60  cclothes
15       rce    20-60  cclothes
16       rce    20-60  cclothes
17       rce    20-60  cclothes
18       rce    20-60  cclothes
    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2  31  26   0  27  0.678571       1.0       0.534483  0.696629
1         3  31  31   0  22  0.738095       1.0       0.584906  0.738095
2         4  31  37   0  16  0.809524       1.0       0.659574  0.794872
3         5  31  40   0  13  0.845238       1.0       0.704545  0.826667
4         6  31  44   0   9  0.892857       1.0       0.775000  0.873239
5         7  31  45   0   8  0.904762       1.0       0.794872  0.885714
6         8  31  45   0   8  0.904762       1.0       0.794872  0.885714
7         9  31  47   0   6  0.928571       1.0       0.837838  0.911765
8        10  31  47   0   6  0.928571       1.0       0.837838  0.911765
9        11  31  47   0   6  0.928571       1.0       0.837838  0.911765
10       12  31  46   0   7  0.916667       1.0       0.815789  0.898551
11       13  31  45   0   8  0.904762       1.0       0.794872  0.885714
12       14  31  45   0   8  0.904762       1.0       0.794872  0.885714
13       15  31  46   0   7  0.916667       1.0       0.815789  0.898551
14       16  31  45   0   8  0.904762       1.0       0.794872  0.885714
15       17  31  47   0   6  0.928571       1.0       0.837838  0.911765
16       18  31  49   0   4  0.952381       1.0       0.885714  0.939394
17       19  31  49   0   4  0.952381       1.0       0.885714  0.939394
18       20  31  51   0   2  0.976190       1.0       0.939394  0.968750

   algoritmo variacao atividade
0      ocsvm    20-60    eating
1      ocsvm    20-60    eating
2      ocsvm    20-60    eating
3      ocsvm    20-60    eating
4      ocsvm    20-60    eating
5      ocsvm    20-60    eating
6      ocsvm    20-60    eating
7      ocsvm    20-60    eating
8      ocsvm    20-60    eating
9      ocsvm    20-60    eating
10     ocsvm    20-60    eating
11     ocsvm    20-60    eating
12     ocsvm    20-60    eating
13     ocsvm    20-60    eating
14     ocsvm    20-60    eating
15     ocsvm    20-60    eating
16     ocsvm    20-60    eating
17     ocsvm    20-60    eating
18     ocsvm    20-60    eating
    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2  25  53   6   0  0.928571  0.806452       1.000000  0.892857
1         3  24  53   7   0  0.916667  0.774194       1.000000  0.872727
2         4  24  53   7   0  0.916667  0.774194       1.000000  0.872727
3         5  26  53   5   0  0.940476  0.838710       1.000000  0.912281
4         6  26  53   5   0  0.940476  0.838710       1.000000  0.912281
5         7  27  53   4   0  0.952381  0.870968       1.000000  0.931034
6         8  27  52   4   1  0.940476  0.870968       0.964286  0.915254
7         9  27  52   4   1  0.940476  0.870968       0.964286  0.915254
8        10  27  50   4   3  0.916667  0.870968       0.900000  0.885246
9        11  28  51   3   2  0.940476  0.903226       0.933333  0.918033
10       12  29  50   2   3  0.940476  0.935484       0.906250  0.920635
11       13  29  50   2   3  0.940476  0.935484       0.906250  0.920635
12       14  30  52   1   1  0.976190  0.967742       0.967742  0.967742
13       15  29  52   2   1  0.964286  0.935484       0.966667  0.950820
14       16  29  52   2   1  0.964286  0.935484       0.966667  0.950820
15       17  29  52   2   1  0.964286  0.935484       0.966667  0.950820
16       18  29  53   2   0  0.976190  0.935484       1.000000  0.966667
17       19  29  52   2   1  0.964286  0.935484       0.966667  0.950820
18       20  30  52   1   1  0.976190  0.967742       0.967742  0.967742

   algoritmo variacao atividade
0        lof    20-60    eating
1        lof    20-60    eating
2        lof    20-60    eating
3        lof    20-60    eating
4        lof    20-60    eating
5        lof    20-60    eating
6        lof    20-60    eating
7        lof    20-60    eating
8        lof    20-60    eating
9        lof    20-60    eating
10       lof    20-60    eating
11       lof    20-60    eating
12       lof    20-60    eating
13       lof    20-60    eating
14       lof    20-60    eating
15       lof    20-60    eating
16       lof    20-60    eating
17       lof    20-60    eating
18       lof    20-60    eating

C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall

    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2  11  46  20   7  0.678571  0.354839       0.611111  0.448980
1         3  11  52  20   1  0.750000  0.354839       0.916667  0.511628
2         4   1  53  30   0  0.642857  0.032258       1.000000  0.062500
3         5   3  53  28   0  0.666667  0.096774       1.000000  0.176471
4         6   2  53  29   0  0.654762  0.064516       1.000000  0.121212
5         7   2  53  29   0  0.654762  0.064516       1.000000  0.121212
6         8   2  53  29   0  0.654762  0.064516       1.000000  0.121212
7         9   5  53  26   0  0.690476  0.161290       1.000000  0.277778
8        10  12  53  19   0  0.773810  0.387097       1.000000  0.558140
9        11  11  53  20   0  0.761905  0.354839       1.000000  0.523810
10       12  14  53  17   0  0.797619  0.451613       1.000000  0.622222
11       13  14  53  17   0  0.797619  0.451613       1.000000  0.622222
12       14  17  53  14   0  0.833333  0.548387       1.000000  0.708333
13       15  17  52  14   1  0.821429  0.548387       0.944444  0.693878
14       16  15  53  16   0  0.809524  0.483871       1.000000  0.652174
15       17  19  53  12   0  0.857143  0.612903       1.000000  0.760000
16       18  23  53   8   0  0.904762  0.741935       1.000000  0.851852
17       19   0  53  31   0  0.630952  0.000000            NaN       NaN
18       20   2  53  29   0  0.654762  0.064516       1.000000  0.121212

   algoritmo variacao atividade
0    iforest    20-60    eating
1    iforest    20-60    eating
2    iforest    20-60    eating
3    iforest    20-60    eating
4    iforest    20-60    eating
5    iforest    20-60    eating
6    iforest    20-60    eating
7    iforest    20-60    eating
8    iforest    20-60    eating
9    iforest    20-60    eating
10   iforest    20-60    eating
11   iforest    20-60    eating
12   iforest    20-60    eating
13   iforest    20-60    eating
14   iforest    20-60    eating
15   iforest    20-60    eating
16   iforest    20-60    eating
17   iforest    20-60    eating
18   iforest    20-60    eating
    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2  31  49   0   4  0.952381  1.000000       0.885714  0.939394
1         3  31  52   0   1  0.988095  1.000000       0.968750  0.984127
2         4  31  53   0   0  1.000000  1.000000       1.000000  1.000000
3         5  30  53   1   0  0.988095  0.967742       1.000000  0.983607
4         6  29  53   2   0  0.976190  0.935484       1.000000  0.966667
5         7  29  53   2   0  0.976190  0.935484       1.000000  0.966667
6         8  30  53   1   0  0.988095  0.967742       1.000000  0.983607
7         9  31  53   0   0  1.000000  1.000000       1.000000  1.000000
8        10  31  53   0   0  1.000000  1.000000       1.000000  1.000000
9        11  31  53   0   0  1.000000  1.000000       1.000000  1.000000
10       12  31  53   0   0  1.000000  1.000000       1.000000  1.000000
11       13  30  53   1   0  0.988095  0.967742       1.000000  0.983607
12       14  31  52   0   1  0.988095  1.000000       0.968750  0.984127
13       15  31  52   0   1  0.988095  1.000000       0.968750  0.984127
14       16  30  53   1   0  0.988095  0.967742       1.000000  0.983607
15       17  30  53   1   0  0.988095  0.967742       1.000000  0.983607
16       18  29  53   2   0  0.976190  0.935484       1.000000  0.966667
17       19  30  53   1   0  0.988095  0.967742       1.000000  0.983607
18       20  30  53   1   0  0.988095  0.967742       1.000000  0.983607

   algoritmo variacao atividade
0        rce    20-60    eating
1        rce    20-60    eating
2        rce    20-60    eating
3        rce    20-60    eating
4        rce    20-60    eating
5        rce    20-60    eating
6        rce    20-60    eating
7        rce    20-60    eating
8        rce    20-60    eating
9        rce    20-60    eating
10       rce    20-60    eating
11       rce    20-60    eating
12       rce    20-60    eating
13       rce    20-60    eating
14       rce    20-60    eating
15       rce    20-60    eating
16       rce    20-60    eating
17       rce    20-60    eating
18       rce    20-60    eating
    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2  32  25   0  27  0.678571   1.00000       0.542373  0.703297
1         3  32  29   0  23  0.726190   1.00000       0.581818  0.735632
2         4  32  27   0  25  0.702381   1.00000       0.561404  0.719101
3         5  32  29   0  23  0.726190   1.00000       0.581818  0.735632
4         6  32  27   0  25  0.702381   1.00000       0.561404  0.719101
5         7  32  35   0  17  0.797619   1.00000       0.653061  0.790123
6         8  32  34   0  18  0.785714   1.00000       0.640000  0.780488
7         9  32  36   0  16  0.809524   1.00000       0.666667  0.800000
8        10  31  40   1  12  0.845238   0.96875       0.720930  0.826667
9        11  31  40   1  12  0.845238   0.96875       0.720930  0.826667
10       12  31  42   1  10  0.869048   0.96875       0.756098  0.849315
11       13  31  43   1   9  0.880952   0.96875       0.775000  0.861111
12       14  31  44   1   8  0.892857   0.96875       0.794872  0.873239
13       15  31  44   1   8  0.892857   0.96875       0.794872  0.873239
14       16  31  43   1   9  0.880952   0.96875       0.775000  0.861111
15       17  31  44   1   8  0.892857   0.96875       0.794872  0.873239
16       18  31  44   1   8  0.892857   0.96875       0.794872  0.873239
17       19  31  43   1   9  0.880952   0.96875       0.775000  0.861111
18       20  31  44   1   8  0.892857   0.96875       0.794872  0.873239

   algoritmo variacao atividade
0      ocsvm    20-60    mcoffe
1      ocsvm    20-60    mcoffe
2      ocsvm    20-60    mcoffe
3      ocsvm    20-60    mcoffe
4      ocsvm    20-60    mcoffe
5      ocsvm    20-60    mcoffe
6      ocsvm    20-60    mcoffe
7      ocsvm    20-60    mcoffe
8      ocsvm    20-60    mcoffe
9      ocsvm    20-60    mcoffe
10     ocsvm    20-60    mcoffe
11     ocsvm    20-60    mcoffe
12     ocsvm    20-60    mcoffe
13     ocsvm    20-60    mcoffe
14     ocsvm    20-60    mcoffe
15     ocsvm    20-60    mcoffe
16     ocsvm    20-60    mcoffe
17     ocsvm    20-60    mcoffe
18     ocsvm    20-60    mcoffe
    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2  13  52  19   0  0.773810   0.40625       1.000000  0.577778
1         3  19  52  13   0  0.845238   0.59375       1.000000  0.745098
2         4  24  52   8   0  0.904762   0.75000       1.000000  0.857143
3         5  25  51   7   1  0.904762   0.78125       0.961538  0.862069
4         6  26  52   6   0  0.928571   0.81250       1.000000  0.896552
5         7  26  52   6   0  0.928571   0.81250       1.000000  0.896552
6         8  25  52   7   0  0.916667   0.78125       1.000000  0.877193
7         9  26  52   6   0  0.928571   0.81250       1.000000  0.896552
8        10  26  52   6   0  0.928571   0.81250       1.000000  0.896552
9        11  27  52   5   0  0.940476   0.84375       1.000000  0.915254
10       12  28  52   4   0  0.952381   0.87500       1.000000  0.933333
11       13  27  52   5   0  0.940476   0.84375       1.000000  0.915254
12       14  28  51   4   1  0.940476   0.87500       0.965517  0.918033
13       15  28  50   4   2  0.928571   0.87500       0.933333  0.903226
14       16  28  50   4   2  0.928571   0.87500       0.933333  0.903226
15       17  28  50   4   2  0.928571   0.87500       0.933333  0.903226
16       18  29  50   3   2  0.940476   0.90625       0.935484  0.920635
17       19  29  49   3   3  0.928571   0.90625       0.906250  0.906250
18       20  29  49   3   3  0.928571   0.90625       0.906250  0.906250

   algoritmo variacao atividade
0        lof    20-60    mcoffe
1        lof    20-60    mcoffe
2        lof    20-60    mcoffe
3        lof    20-60    mcoffe
4        lof    20-60    mcoffe
5        lof    20-60    mcoffe
6        lof    20-60    mcoffe
7        lof    20-60    mcoffe
8        lof    20-60    mcoffe
9        lof    20-60    mcoffe
10       lof    20-60    mcoffe
11       lof    20-60    mcoffe
12       lof    20-60    mcoffe
13       lof    20-60    mcoffe
14       lof    20-60    mcoffe
15       lof    20-60    mcoffe
16       lof    20-60    mcoffe
17       lof    20-60    mcoffe
18       lof    20-60    mcoffe

C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:134: RuntimeWarning: invalid value encountered in double_scalars
  f1escore = 2 * ((precisao * sensibilidade)/(precisao + sensibilidade))
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:134: RuntimeWarning: invalid value encountered in double_scalars
  f1escore = 2 * ((precisao * sensibilidade)/(precisao + sensibilidade))
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall

    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2   1  52  31   0  0.630952   0.03125       1.000000  0.060606
1         3   4  51  28   1  0.654762   0.12500       0.800000  0.216216
2         4   7  49  25   3  0.666667   0.21875       0.700000  0.333333
3         5   0  51  32   1  0.607143   0.00000       0.000000       NaN
4         6   0  52  32   0  0.619048   0.00000            NaN       NaN
5         7   0  52  32   0  0.619048   0.00000            NaN       NaN
6         8   0  52  32   0  0.619048   0.00000            NaN       NaN
7         9   0  52  32   0  0.619048   0.00000            NaN       NaN
8        10   0  51  32   1  0.607143   0.00000       0.000000       NaN
9        11   0  52  32   0  0.619048   0.00000            NaN       NaN
10       12   0  52  32   0  0.619048   0.00000            NaN       NaN
11       13   0  52  32   0  0.619048   0.00000            NaN       NaN
12       14   0  52  32   0  0.619048   0.00000            NaN       NaN
13       15   0  52  32   0  0.619048   0.00000            NaN       NaN
14       16   2  51  30   1  0.630952   0.06250       0.666667  0.114286
15       17   2  52  30   0  0.642857   0.06250       1.000000  0.117647
16       18   2  52  30   0  0.642857   0.06250       1.000000  0.117647
17       19   2  51  30   1  0.630952   0.06250       0.666667  0.114286
18       20   4  52  28   0  0.666667   0.12500       1.000000  0.222222

   algoritmo variacao atividade
0    iforest    20-60    mcoffe
1    iforest    20-60    mcoffe
2    iforest    20-60    mcoffe
3    iforest    20-60    mcoffe
4    iforest    20-60    mcoffe
5    iforest    20-60    mcoffe
6    iforest    20-60    mcoffe
7    iforest    20-60    mcoffe
8    iforest    20-60    mcoffe
9    iforest    20-60    mcoffe
10   iforest    20-60    mcoffe
11   iforest    20-60    mcoffe
12   iforest    20-60    mcoffe
13   iforest    20-60    mcoffe
14   iforest    20-60    mcoffe
15   iforest    20-60    mcoffe
16   iforest    20-60    mcoffe
17   iforest    20-60    mcoffe
18   iforest    20-60    mcoffe
    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2  19  52  13   0  0.845238   0.59375       1.000000  0.745098
1         3  17  52  15   0  0.821429   0.53125       1.000000  0.693878
2         4  18  52  14   0  0.833333   0.56250       1.000000  0.720000
3         5  28  50   4   2  0.928571   0.87500       0.933333  0.903226
4         6  26  51   6   1  0.916667   0.81250       0.962963  0.881356
5         7  26  52   6   0  0.928571   0.81250       1.000000  0.896552
6         8  26  52   6   0  0.928571   0.81250       1.000000  0.896552
7         9  26  52   6   0  0.928571   0.81250       1.000000  0.896552
8        10  26  52   6   0  0.928571   0.81250       1.000000  0.896552
9        11  26  52   6   0  0.928571   0.81250       1.000000  0.896552
10       12  25  52   7   0  0.916667   0.78125       1.000000  0.877193
11       13  26  52   6   0  0.928571   0.81250       1.000000  0.896552
12       14  26  52   6   0  0.928571   0.81250       1.000000  0.896552
13       15  26  52   6   0  0.928571   0.81250       1.000000  0.896552
14       16  26  52   6   0  0.928571   0.81250       1.000000  0.896552
15       17  26  52   6   0  0.928571   0.81250       1.000000  0.896552
16       18  26  52   6   0  0.928571   0.81250       1.000000  0.896552
17       19  26  52   6   0  0.928571   0.81250       1.000000  0.896552
18       20  26  52   6   0  0.928571   0.81250       1.000000  0.896552

   algoritmo variacao atividade
0        rce    20-60    mcoffe
1        rce    20-60    mcoffe
2        rce    20-60    mcoffe
3        rce    20-60    mcoffe
4        rce    20-60    mcoffe
5        rce    20-60    mcoffe
6        rce    20-60    mcoffe
7        rce    20-60    mcoffe
8        rce    20-60    mcoffe
9        rce    20-60    mcoffe
10       rce    20-60    mcoffe
11       rce    20-60    mcoffe
12       rce    20-60    mcoffe
13       rce    20-60    mcoffe
14       rce    20-60    mcoffe
15       rce    20-60    mcoffe
16       rce    20-60    mcoffe
17       rce    20-60    mcoffe
18       rce    20-60    mcoffe
    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade  f1score  \
0         2  22  26   0   0       1.0       1.0            1.0      1.0
1         3  22  37   0   0       1.0       1.0            1.0      1.0
2         4  22  39   0   0       1.0       1.0            1.0      1.0
3         5  22  39   0   0       1.0       1.0            1.0      1.0
4         6  22  42   0   0       1.0       1.0            1.0      1.0
5         7  22  41   0   0       1.0       1.0            1.0      1.0
6         8  22  41   0   0       1.0       1.0            1.0      1.0
7         9  22  41   0   0       1.0       1.0            1.0      1.0
8        10  22  41   0   0       1.0       1.0            1.0      1.0
9        11  22  41   0   0       1.0       1.0            1.0      1.0
10       12  22  43   0   0       1.0       1.0            1.0      1.0
11       13  22  43   0   0       1.0       1.0            1.0      1.0
12       14  22  43   0   0       1.0       1.0            1.0      1.0
13       15  22  46   0   0       1.0       1.0            1.0      1.0
14       16  22  51   0   0       1.0       1.0            1.0      1.0
15       17  22  50   0   0       1.0       1.0            1.0      1.0
16       18  22  49   0   0       1.0       1.0            1.0      1.0
17       19  22  49   0   0       1.0       1.0            1.0      1.0
18       20  22  46   0   0       1.0       1.0            1.0      1.0

   algoritmo variacao atividade
0      ocsvm    20-60  mhotfood
1      ocsvm    20-60  mhotfood
2      ocsvm    20-60  mhotfood
3      ocsvm    20-60  mhotfood
4      ocsvm    20-60  mhotfood
5      ocsvm    20-60  mhotfood
6      ocsvm    20-60  mhotfood
7      ocsvm    20-60  mhotfood
8      ocsvm    20-60  mhotfood
9      ocsvm    20-60  mhotfood
10     ocsvm    20-60  mhotfood
11     ocsvm    20-60  mhotfood
12     ocsvm    20-60  mhotfood
13     ocsvm    20-60  mhotfood
14     ocsvm    20-60  mhotfood
15     ocsvm    20-60  mhotfood
16     ocsvm    20-60  mhotfood
17     ocsvm    20-60  mhotfood
18     ocsvm    20-60  mhotfood
    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2   6  62  16   0  0.809524  0.272727            1.0  0.428571
1         3  10  62  12   0  0.857143  0.454545            1.0  0.625000
2         4  12  62  10   0  0.880952  0.545455            1.0  0.705882
3         5  12  62  10   0  0.880952  0.545455            1.0  0.705882
4         6  14  62   8   0  0.904762  0.636364            1.0  0.777778
5         7  14  61   8   0  0.903614  0.636364            1.0  0.777778
6         8  16  60   6   0  0.926829  0.727273            1.0  0.842105
7         9  18  60   4   0  0.951220  0.818182            1.0  0.900000
8        10  18  61   4   0  0.951807  0.818182            1.0  0.900000
9        11  19  62   3   0  0.964286  0.863636            1.0  0.926829
10       12  19  62   3   0  0.964286  0.863636            1.0  0.926829
11       13  19  62   3   0  0.964286  0.863636            1.0  0.926829
12       14  18  61   4   0  0.951807  0.818182            1.0  0.900000
13       15  18  61   4   0  0.951807  0.818182            1.0  0.900000
14       16  18  61   4   0  0.951807  0.818182            1.0  0.900000
15       17  19  61   3   0  0.963855  0.863636            1.0  0.926829
16       18  19  60   3   0  0.963415  0.863636            1.0  0.926829
17       19  19  61   3   0  0.963855  0.863636            1.0  0.926829
18       20  19  61   3   0  0.963855  0.863636            1.0  0.926829

   algoritmo variacao atividade
0        lof    20-60  mhotfood
1        lof    20-60  mhotfood
2        lof    20-60  mhotfood
3        lof    20-60  mhotfood
4        lof    20-60  mhotfood
5        lof    20-60  mhotfood
6        lof    20-60  mhotfood
7        lof    20-60  mhotfood
8        lof    20-60  mhotfood
9        lof    20-60  mhotfood
10       lof    20-60  mhotfood
11       lof    20-60  mhotfood
12       lof    20-60  mhotfood
13       lof    20-60  mhotfood
14       lof    20-60  mhotfood
15       lof    20-60  mhotfood
16       lof    20-60  mhotfood
17       lof    20-60  mhotfood
18       lof    20-60  mhotfood

    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2   6  46  16   0  0.764706  0.272727            1.0  0.428571
1         3   3  58  19   0  0.762500  0.136364            1.0  0.240000
2         4   2  58  20   0  0.750000  0.090909            1.0  0.166667
3         5   7  55  15   0  0.805195  0.318182            1.0  0.482759
4         6   6  55  16   0  0.792208  0.272727            1.0  0.428571
5         7   4  58  18   0  0.775000  0.181818            1.0  0.307692
6         8   3  58  19   0  0.762500  0.136364            1.0  0.240000
7         9   4  58  18   0  0.775000  0.181818            1.0  0.307692
8        10   4  58  18   0  0.775000  0.181818            1.0  0.307692
9        11   2  59  20   0  0.753086  0.090909            1.0  0.166667
10       12   2  60  20   0  0.756098  0.090909            1.0  0.166667
11       13   2  57  20   0  0.746835  0.090909            1.0  0.166667
12       14   2  58  20   0  0.750000  0.090909            1.0  0.166667
13       15   2  58  20   0  0.750000  0.090909            1.0  0.166667
14       16   2  58  20   0  0.750000  0.090909            1.0  0.166667
15       17   2  58  20   0  0.750000  0.090909            1.0  0.166667
16       18   2  58  20   0  0.750000  0.090909            1.0  0.166667
17       19   3  58  19   0  0.762500  0.136364            1.0  0.240000
18       20   5  59  17   0  0.790123  0.227273            1.0  0.370370

   algoritmo variacao atividade
0    iforest    20-60  mhotfood
1    iforest    20-60  mhotfood
2    iforest    20-60  mhotfood
3    iforest    20-60  mhotfood
4    iforest    20-60  mhotfood
5    iforest    20-60  mhotfood
6    iforest    20-60  mhotfood
7    iforest    20-60  mhotfood
8    iforest    20-60  mhotfood
9    iforest    20-60  mhotfood
10   iforest    20-60  mhotfood
11   iforest    20-60  mhotfood
12   iforest    20-60  mhotfood
13   iforest    20-60  mhotfood
14   iforest    20-60  mhotfood
15   iforest    20-60  mhotfood
16   iforest    20-60  mhotfood
17   iforest    20-60  mhotfood
18   iforest    20-60  mhotfood
    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2  19  44   3   0  0.954545  0.863636            1.0  0.926829
1         3  20  55   2   0  0.974026  0.909091            1.0  0.952381
2         4  22  52   0   0  1.000000  1.000000            1.0  1.000000
3         5  22  59   0   0  1.000000  1.000000            1.0  1.000000
4         6  22  54   0   0  1.000000  1.000000            1.0  1.000000
5         7  20  57   2   0  0.974684  0.909091            1.0  0.952381
6         8  13  55   9   0  0.883117  0.590909            1.0  0.742857
7         9  12  57  10   0  0.873418  0.545455            1.0  0.705882
8        10  17  57   5   0  0.936709  0.772727            1.0  0.871795
9        11  13  57   9   0  0.886076  0.590909            1.0  0.742857
10       12   9  57  13   0  0.835443  0.409091            1.0  0.580645
11       13   7  57  15   0  0.810127  0.318182            1.0  0.482759
12       14   7  57  15   0  0.810127  0.318182            1.0  0.482759
13       15   7  57  15   0  0.810127  0.318182            1.0  0.482759
14       16   7  57  15   0  0.810127  0.318182            1.0  0.482759
15       17   7  57  15   0  0.810127  0.318182            1.0  0.482759
16       18   7  57  15   0  0.810127  0.318182            1.0  0.482759
17       19   7  57  15   0  0.810127  0.318182            1.0  0.482759
18       20  10  57  12   0  0.848101  0.454545            1.0  0.625000

   algoritmo variacao atividade
0        rce    20-60  mhotfood
1        rce    20-60  mhotfood
2        rce    20-60  mhotfood
3        rce    20-60  mhotfood
4        rce    20-60  mhotfood
5        rce    20-60  mhotfood
6        rce    20-60  mhotfood
7        rce    20-60  mhotfood
8        rce    20-60  mhotfood
9        rce    20-60  mhotfood
10       rce    20-60  mhotfood
11       rce    20-60  mhotfood
12       rce    20-60  mhotfood
13       rce    20-60  mhotfood
14       rce    20-60  mhotfood
15       rce    20-60  mhotfood
16       rce    20-60  mhotfood
17       rce    20-60  mhotfood
18       rce    20-60  mhotfood
    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2  32  22   0   0  1.000000   1.00000            1.0  1.000000
1         3  31  24   1   0  0.982143   0.96875            1.0  0.984127
2         4  31  29   1   0  0.983607   0.96875            1.0  0.984127
3         5  31  30   1   0  0.983871   0.96875            1.0  0.984127
4         6  31  33   1   0  0.984615   0.96875            1.0  0.984127
5         7  31  36   1   0  0.985294   0.96875            1.0  0.984127
6         8  31  35   1   0  0.985075   0.96875            1.0  0.984127
7         9  31  36   1   0  0.985294   0.96875            1.0  0.984127
8        10  31  37   1   0  0.985507   0.96875            1.0  0.984127
9        11  31  39   1   0  0.985915   0.96875            1.0  0.984127
10       12  31  39   1   0  0.985915   0.96875            1.0  0.984127
11       13  31  39   1   0  0.985915   0.96875            1.0  0.984127
12       14  31  39   1   0  0.985915   0.96875            1.0  0.984127
13       15  32  39   0   0  1.000000   1.00000            1.0  1.000000
14       16  32  41   0   0  1.000000   1.00000            1.0  1.000000
15       17  32  41   0   0  1.000000   1.00000            1.0  1.000000
16       18  32  40   0   0  1.000000   1.00000            1.0  1.000000
17       19  32  43   0   0  1.000000   1.00000            1.0  1.000000
18       20  32  41   0   0  1.000000   1.00000            1.0  1.000000

   algoritmo variacao  atividade
0      ocsvm    20-60  toileting
1      ocsvm    20-60  toileting
2      ocsvm    20-60  toileting
3      ocsvm    20-60  toileting
4      ocsvm    20-60  toileting
5      ocsvm    20-60  toileting
6      ocsvm    20-60  toileting
7      ocsvm    20-60  toileting
8      ocsvm    20-60  toileting
9      ocsvm    20-60  toileting
10     ocsvm    20-60  toileting
11     ocsvm    20-60  toileting
12     ocsvm    20-60  toileting
13     ocsvm    20-60  toileting
14     ocsvm    20-60  toileting
15     ocsvm    20-60  toileting
16     ocsvm    20-60  toileting
17     ocsvm    20-60  toileting
18     ocsvm    20-60  toileting
    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2  24  52   8   0  0.904762   0.75000            1.0  0.857143
1         3  30  52   2   0  0.976190   0.93750            1.0  0.967742
2         4  30  50   2   0  0.975610   0.93750            1.0  0.967742
3         5  30  49   2   0  0.975309   0.93750            1.0  0.967742
4         6  30  52   2   0  0.976190   0.93750            1.0  0.967742
5         7  30  52   2   0  0.976190   0.93750            1.0  0.967742
6         8  30  52   2   0  0.976190   0.93750            1.0  0.967742
7         9  30  52   2   0  0.976190   0.93750            1.0  0.967742
8        10  30  51   2   0  0.975904   0.93750            1.0  0.967742
9        11  30  52   2   0  0.976190   0.93750            1.0  0.967742
10       12  30  52   2   0  0.976190   0.93750            1.0  0.967742
11       13  30  49   2   0  0.975309   0.93750            1.0  0.967742
12       14  31  48   1   0  0.987500   0.96875            1.0  0.984127
13       15  31  49   1   0  0.987654   0.96875            1.0  0.984127
14       16  31  51   1   0  0.987952   0.96875            1.0  0.984127
15       17  31  50   1   0  0.987805   0.96875            1.0  0.984127
16       18  31  51   1   0  0.987952   0.96875            1.0  0.984127
17       19  31  51   1   0  0.987952   0.96875            1.0  0.984127
18       20  31  51   1   0  0.987952   0.96875            1.0  0.984127

   algoritmo variacao  atividade
0        lof    20-60  toileting
1        lof    20-60  toileting
2        lof    20-60  toileting
3        lof    20-60  toileting
4        lof    20-60  toileting
5        lof    20-60  toileting
6        lof    20-60  toileting
7        lof    20-60  toileting
8        lof    20-60  toileting
9        lof    20-60  toileting
10       lof    20-60  toileting
11       lof    20-60  toileting
12       lof    20-60  toileting
13       lof    20-60  toileting
14       lof    20-60  toileting
15       lof    20-60  toileting
16       lof    20-60  toileting
17       lof    20-60  toileting
18       lof    20-60  toileting

C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall
C:\Users\mauri\AppData\Local\Temp\ipykernel_26332\1133002495.py:133: RuntimeWarning: invalid value encountered in longlong_scalars
  sensibilidade = VP/(FN+VP) #recall

    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2   5  51  27   0  0.674699   0.15625            1.0  0.270270
1         3   0  51  32   0  0.614458   0.00000            NaN       NaN
2         4   0  50  32   0  0.609756   0.00000            NaN       NaN
3         5   0  51  32   0  0.614458   0.00000            NaN       NaN
4         6   3  52  29   0  0.654762   0.09375            1.0  0.171429
5         7   4  52  28   0  0.666667   0.12500            1.0  0.222222
6         8   3  52  29   0  0.654762   0.09375            1.0  0.171429
7         9   0  52  32   0  0.619048   0.00000            NaN       NaN
8        10   0  52  32   0  0.619048   0.00000            NaN       NaN
9        11   6  52  26   0  0.690476   0.18750            1.0  0.315789
10       12   7  52  25   0  0.702381   0.21875            1.0  0.358974
11       13   7  50  25   0  0.695122   0.21875            1.0  0.358974
12       14   6  50  26   0  0.682927   0.18750            1.0  0.315789
13       15   6  52  26   0  0.690476   0.18750            1.0  0.315789
14       16   6  52  26   0  0.690476   0.18750            1.0  0.315789
15       17   6  52  26   0  0.690476   0.18750            1.0  0.315789
16       18   7  52  25   0  0.702381   0.21875            1.0  0.358974
17       19   7  52  25   0  0.702381   0.21875            1.0  0.358974
18       20   7  52  25   0  0.702381   0.21875            1.0  0.358974

   algoritmo variacao  atividade
0    iforest    20-60  toileting
1    iforest    20-60  toileting
2    iforest    20-60  toileting
3    iforest    20-60  toileting
4    iforest    20-60  toileting
5    iforest    20-60  toileting
6    iforest    20-60  toileting
7    iforest    20-60  toileting
8    iforest    20-60  toileting
9    iforest    20-60  toileting
10   iforest    20-60  toileting
11   iforest    20-60  toileting
12   iforest    20-60  toileting
13   iforest    20-60  toileting
14   iforest    20-60  toileting
15   iforest    20-60  toileting
16   iforest    20-60  toileting
17   iforest    20-60  toileting
18   iforest    20-60  toileting
    semanas  vp  vn  fp  fn  acuracia  precisao  sensibilidade   f1score  \
0         2  25  52   7   0  0.916667   0.78125            1.0  0.877193
1         3  27  51   5   0  0.939759   0.84375            1.0  0.915254
2         4  32  49   0   0  1.000000   1.00000            1.0  1.000000
3         5  32  50   0   0  1.000000   1.00000            1.0  1.000000
4         6  32  50   0   0  1.000000   1.00000            1.0  1.000000
5         7  32  51   0   0  1.000000   1.00000            1.0  1.000000
6         8  32  51   0   0  1.000000   1.00000            1.0  1.000000
7         9  32  51   0   0  1.000000   1.00000            1.0  1.000000
8        10  32  50   0   0  1.000000   1.00000            1.0  1.000000
9        11  32  50   0   0  1.000000   1.00000            1.0  1.000000
10       12  32  50   0   0  1.000000   1.00000            1.0  1.000000
11       13  32  49   0   0  1.000000   1.00000            1.0  1.000000
12       14  32  49   0   0  1.000000   1.00000            1.0  1.000000
13       15  31  50   1   0  0.987805   0.96875            1.0  0.984127
14       16  30  50   2   0  0.975610   0.93750            1.0  0.967742
15       17  30  50   2   0  0.975610   0.93750            1.0  0.967742
16       18  31  50   1   0  0.987805   0.96875            1.0  0.984127
17       19  30  50   2   0  0.975610   0.93750            1.0  0.967742
18       20  31  50   1   0  0.987805   0.96875            1.0  0.984127

   algoritmo variacao  atividade
0        rce    20-60  toileting
1        rce    20-60  toileting
2        rce    20-60  toileting
3        rce    20-60  toileting
4        rce    20-60  toileting
5        rce    20-60  toileting
6        rce    20-60  toileting
7        rce    20-60  toileting
8        rce    20-60  toileting
9        rce    20-60  toileting
10       rce    20-60  toileting
11       rce    20-60  toileting
12       rce    20-60  toileting
13       rce    20-60  toileting
14       rce    20-60  toileting
15       rce    20-60  toileting
16       rce    20-60  toileting
17       rce    20-60  toileting
18       rce    20-60  toileting

In [35]:
print('DONE')

DONE